### ISSUE TITLE
How should I run this project

### ISSUE THREAD

**Issue by KomicaReborn** [Zilleplus/PANOCSharp#1]

**Comment by MelisWillem** [comment]
This is a dotnet core project, 

If you are using Windows or Mac you can install visual studio community with the C#.NET core toolset. 

If you are using Linux(this also works on mac or windows) install dotnet core. The navigate in the command line to the demo project and run "dotnet run". I recommend installing "visual studio code" to get a nice debugger but it's not required.

dotnet core sdk : https://dotnet.microsoft.com/download 
visual studio community: https://visualstudio.microsoft.com/vs/
visual studio core: https://code.visualstudio.com/
