### ISSUE TITLE
Where can I find the definition of x in the costFunction

### ISSUE THREAD

**Issue by KomicaReborn** [Zilleplus/PANOCSharp#2]

**Comment by MelisWillem** [comment]
A cost function should implement [IFunction](https://github.com/Zilleplus/PANOCSharp/blob/master/src/kul.forbes.contracts/IFunction.cs ), It has to provide an implementation for Evaluate, Evaluate takes in a position, this is your x.

There are 2 generic cost function implementations that take lambda's in their constructor:
[Function.cs](https://github.com/Zilleplus/PANOCSharp/blob/master/src/kul.forbes/Function.cs)
