### ISSUE TITLE
 I have some questions about demo.

### ISSUE THREAD

**Issue by KomicaReborn** [Zilleplus/PANOCSharp#3]
If I want to solve a nonlinear programming problem, how should I set costfunction, constraint and defaultconfig? I can't understand the bottom layer of these functions very well.

**Comment by MelisWillem** [comment]
Ok so the demo looks like this:
```
var degree = 2;
var costFunction = new VectorFunction(x => (x.PointwisePower(degree).Sum(), degree * x.PointwisePower(degree - 1)));
var constraint = new ProxBox(size: 1, penalty: 1, dimension: 2);
var defaultConfig = new ConfigPanoc(problemDimension: 2);

var solver = new PANOCSolver(costFunction,constraint,defaultConfig);
var solution = solver.Solve(new double[] { 1.0,1.0 });
```
The cost functions here is defined use a vector function, i gives you access to a lin algebra lib, If you don't want lin algebra, you can use the class "Function". It uses C# array's.

The constrain is a box function here, at the moment I don't provide any other constraints, but if you look inside the ProxBox, it's quiet easy to construct your own constraint. The box function constraint basically means "stay inside these borders with your solution".

The defaultConfig you should mostly leave alone, except for the dimension parameter, as is done in the demo. I will add a bit of doc's here, but for now you can find a nice summary on the config [interfaces here](https://github.com/Zilleplus/PANOCSharp/tree/master/src/kul.forbes.contracts/configs), if you want to know what all the parameters mean.

**Comment by MelisWillem** [comment]
@KomicaReborn maybe you can try with some problem you like. It's easier for me to help you if you post some code. Then i can also see where the API is confusing.

**Comment by KomicaReborn** [comment]
> @KomicaReborn maybe you can try with some problem you like. It's easier for me to help you if you post some code. Then i can also see where the API is confusing.

I'm just a beginner of NMPC, and I haven't been exposed to C# before. What I want to do now is to use your solver to solve the NMPC obstacle avoidance problem. If so, does the underlying code should be modified?

**Comment by MelisWillem** [comment]
@KomicaReborn well you need to define the cost function. Maybe start without obstacle avoidance. This is just the solver, it does no nmpc, you need to do that yourself. The solver simply finds the minimum of some cost function and nothing more.

**Comment by KomicaReborn** [comment]
But where should I change the X in the cost function？

**Comment by KomicaReborn** [comment]
> @KomicaReborn well you need to define the cost function. Maybe start without obstacle avoidance. This is just the solver, it does no nmpc, you need to do that yourself. The solver simply finds the minimum of some cost function and nothing more.

And what is the degree's meaning?

**Comment by MelisWillem** [comment]
@KomicaReborn I think this might be a bit too bare-bones for you at the moment. You should take a look at [Casadi](https://github.com/casadi/casadi) they provide a solution where everyting is hidden. And you can call it from python, simple to setup and to use.

Maybe try to do your problem over there first and post it on github, then we can try to get that problem as a demo here.

**Comment by KomicaReborn** [comment]
@Zilleplus guys where can I find the document that you add recently？

**Comment by MelisWillem** [comment]
@KomicaReborn  haven't gotten to it yet, but look at the interfaces. Il simply be copying it from the interfaces.

**Comment by MelisWillem** [comment]
docs are available under doc folder
