### ISSUE TITLE
Add documentation

### ISSUE THREAD

**Issue by MelisWillem** [Zilleplus/PANOCSharp#4]
- explain the demo
- show how constraint's can be added
- show how to create cost functions

**Comment by KomicaReborn** [comment]
Where can I find it？

**Comment by MelisWillem** [comment]
it's open issue, todo..

**Comment by KomicaReborn** [comment]
OK, what a pity. Maybe I can send my cost function and costraint here so that you can use them to make a new demo?

**Comment by MelisWillem** [comment]
@KomicaReborn  sure thing, alway's open to more demo's/examples

**Comment by MelisWillem** [comment]
@KomicaReborn  made a branch for this with new project in it, let's do this! Was going to create such an example anyway, it's alway's nice if i can split the work.

**Comment by MelisWillem** [comment]
the branch is called :  feature/add-nmpc-demo-with-panoc

**Comment by MelisWillem** [comment]
basic doc's have been added under the doc's folder.

**Comment by MelisWillem** [comment]
@KomicaReborn  closing the issue here and opening a new one for a nmpc demo
